version: "3"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE_LOCAL: shortlink
      POSTGRES_DB: shortlink
      POSTGRES_HOST_LOCAL: localhost
      POSTGRES_PASSWORD_LOCAL: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_LOCAL: 5432
      POSTGRES_USER_LOCAL: postgres
    ports:
      - "9999:5432"
    networks:
      - network
  node:
    image: node:18.18.0
    environment:
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_PORT: "postgres"
      DATABASE_NAME: "postgres"
      DATABASE_HOST: "localhost"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - network
    env_file: .env
    volumes:
      - .:/home/node/app
    command:
      - npm install
      - npm run tests

networks:
  network:
    driver: bridge