version: "3"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE_LOCAL: auth
      POSTGRES_DB: auth
      POSTGRES_HOST_LOCAL: localhost
      POSTGRES_PASSWORD_LOCAL: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_LOCAL: 9999
      POSTGRES_USER_LOCAL: postgres
    ports:
      - "9999:5432"
    networks:
      - network

networks:
  network:
    driver: bridge