GET http://localhost:5000/users
Content-Type: application/json
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGUiLCJlbWFpbCI6InRlc3RlQHRlc3RlLmNvbS5iciIsImlkIjoiMDE4YmY5NDgtMDQ4NC03ODc2LTljZGYtOWVhODNkMDJlZjIwIiwicm9sZXMiOlsidXNlci5nZXRpbmZvIl0sImlhdCI6MTcwMDY5NzIxNiwiZXhwIjoxNzAwNzAwODE2LCJpc3MiOiIwMThiZDRmNC1kZjg0LTc4ZmItYjUyOS00ZDlhZTcxYmU5N2IifQ.XSS1gmaYtuh4TWn34pMmoEIC50E0c2ZUwxLC8vgEtR0
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGUiLCJlbWFpbCI6InRlc3RlQHRlc3RlLmNvbS5iciIsImlkIjoiMDE4YmY5NDgtMDQ4NC03ODc2LTljZGYtOWVhODNkMDJlZjIwIiwicm9sZXMiOlsiYWRtaW4udXNlciJdLCJpYXQiOjE3MDA2OTc4MDMsImV4cCI6MTcwMDcwMTQwMywiaXNzIjoiMDE4YmQ0ZjQtZGY4NC03OGZiLWI1MjktNGQ5YWU3MWJlOTdiIn0.cegGaS8maYMB3f3nFu48ekc7qFeyXNt0dALiHutZqMQ
